import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Curated Elegance — Stitch Design System
        "primary": "#e75a66",
        "on-primary": "#ffffff",
        "primary-container": "#cb4552",
        "on-primary-container": "#fffbff",
        "primary-fixed": "#ffdada",
        "primary-fixed-dim": "#ffb3b4",
        "on-primary-fixed": "#40000b",
        "on-primary-fixed-variant": "#8c1429",
        "inverse-primary": "#ffb3b4",
        "surface-tint": "#ad2f3e",

        "secondary": "#8d4c41",
        "on-secondary": "#ffffff",
        "secondary-container": "#ffac9d",
        "on-secondary-container": "#7a3d33",
        "secondary-fixed": "#ffdad4",
        "secondary-fixed-dim": "#ffb4a6",
        "on-secondary-fixed": "#390b05",
        "on-secondary-fixed-variant": "#70362b",

        "tertiary": "#006a43",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#008656",
        "on-tertiary-container": "#f6fff6",
        "tertiary-fixed": "#7ffaba",
        "tertiary-fixed-dim": "#61dda0",
        "on-tertiary-fixed": "#002112",
        "on-tertiary-fixed-variant": "#005233",

        "surface": "#fbf9f8",
        "surface-dim": "#dcd9d9",
        "surface-bright": "#fbf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae8e7",
        "surface-container-highest": "#e4e2e1",
        "surface-variant": "#e4e2e1",
        "on-surface": "#1b1c1c",
        "on-surface-variant": "#584141",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f3f0f0",
        "background": "#fbf9f8",
        "on-background": "#1b1c1c",
        "surface-tint-color": "#ad2f3e",

        "outline": "#8c7171",
        "outline-variant": "#dfbfbf",

        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "unit": "8px",
        "gutter": "16px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "stack-xl": "64px",
        "container-margin-mobile": "24px",
        "container-margin-desktop": "64px",
      },
      fontFamily: {
        sans: ["Montserrat", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "body-lg": ["Montserrat", "sans-serif"],
        "body-md": ["Montserrat", "sans-serif"],
        "label-md": ["Montserrat", "sans-serif"],
        "label-sm": ["Montserrat", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      boxShadow: {
        "ambient": "0 20px 40px rgba(51, 51, 51, 0.04)",
        "ambient-md": "0 10px 30px rgba(51, 51, 51, 0.06)",
        "primary-glow": "0 8px 24px rgba(231, 90, 102, 0.20)",
        "nav": "0 -4px 20px 0 rgba(27, 28, 28, 0.03)",
      },
    },
  },
  plugins: [],
};

export default config;
