import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#6ffbbe",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-highest": "#353534",
        "outline": "#908fa0",
        "surface": "#131313",
        "tertiary": "#ddb7ff",
        "surface-container": "#201f1f",
        "on-surface-variant": "#c7c4d7",
        "primary-container": "#8083ff",
        "secondary": "#4edea3",
        "tertiary-container": "#b76dff",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-secondary-container": "#00311f",
        "inverse-on-surface": "#313030",
        "error": "#ffb4ab",
        "surface-bright": "#3a3939",
        "secondary-container": "#00a572",
        "on-tertiary": "#490080",
        "primary-fixed": "#e1e0ff",
        "on-primary": "#1000a9",
        "surface-container-high": "#2a2a2a",
        "primary": "#c0c1ff",
        "on-error": "#690005",
        "tertiary-fixed-dim": "#ddb7ff",
        "on-tertiary-fixed": "#2c0051",
        "on-secondary-fixed-variant": "#005236",
        "on-primary-fixed": "#07006c",
        "outline-variant": "#464554",
        "on-tertiary-container": "#400071",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed": "#002113",
        "surface-container-low": "#1c1b1b",
        "surface-dim": "#131313",
        "inverse-primary": "#494bd6",
        "on-tertiary-fixed-variant": "#6900b3",
        "surface-tint": "#c0c1ff",
        "surface-variant": "#353534",
        "on-surface": "#e5e2e1",
        "inverse-surface": "#e5e2e1",
        "error-container": "#93000a",
        "tertiary-fixed": "#f0dbff",
        "on-background": "#e5e2e1",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary": "#003824",
        "on-primary-container": "#0d0096",
        "background": "#131313",
      },
      spacing: {
        "stack-lg": "32px",
        "stack-md": "16px",
        "container-margin": "20px",
        "stack-sm": "8px",
        "unit": "4px",
        "gutter": "16px",
      },
      fontFamily: {
        "body-md": ["var(--font-inter)"],
        "headline-lg-mobile": ["var(--font-sora)"],
        "label-md": ["var(--font-inter)"],
        "headline-md": ["var(--font-sora)"],
        "headline-lg": ["var(--font-sora)"],
        "display": ["var(--font-sora)"],
        "body-lg": ["var(--font-inter)"],
        "label-sm": ["var(--font-inter)"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
